### ISSUE TITLE
Requiremets.txt file

### ISSUE THREAD

**Issue by AkshayJainG** [fellchase/flumberboozle#1]
Hi 

Is there any requirements.txt file present for flumberbuckets?

**Comment by fellchase** [comment]
Hi

No I actually forgot to include requirements.txt file in the repository, to
be honest I don't think it's needed as you can see in the installation
instructions that only a few dependencies are required for flumberbuckets!

threading, argparse, subprocess, os, sys, queue are part of standard
library of python, they're pre-installed

While botocore is not part of default python installation but on most Linux
systems you'll get it when you install aws-cli package.
Once you get the aws-cli tool working that is you can run command like
aws s3 ls s3://flaws.cloud
and get output like the following which shows the files currently in the
bucket then you can start using the script

2017-03-14 08:30:38       2575 hint1.html
2017-03-03 09:35:17       1707 hint2.html
2017-03-03 09:35:11       1101 hint3.html
2018-07-10 22:17:16       3082 index.html
2018-07-10 22:17:16      15979 logo.png
2017-02-27 07:29:28         46 robots.txt
2017-02-27 07:29:30       1051 secret-dd02c7c.html

Currently I'm using arch linux and I have following version of aws-cli
installed
bash_command > aws --version
aws-cli/1.16.303 Python/3.8.0 Linux/5.4.3-arch1-1 botocore/1.13.39

In Arch Linux you can install aws-cli using following command
sudo pacman -S aws-cli

For other Linux distributions you can just google on how to install aws-cli
on them or refer to this article
https://www.slashroot.in/how-to-install-and-configure-aws-cli-on-ubuntu-16-04

And yes you'll have to install aws-cli because after flumberbuckets is done
you'll have to manually check if contents of buckets are sensitive or not
for that you'll end up using aws-cli so go ahead and install aws-cli and
botocore will come along with it. So naturally all the dependencies and
requirements would be taken care of :)

Hope this resolved your query.

**Comment by fellchase** [comment]
Thanks for bringing this issue to my notice
Check out new installation instructions on the blogpost :) it has been updated. If you encounter any new problem then create new issue
