### ISSUE TITLE
ACL permission query

### ISSUE THREAD

**Issue by saurabh96216** [fellchase/flumberboozle#3]
Found few ACL permissions enabled in few buckets but not sure what vulnerability I can check with ACL permissions enabled (all other checks are in grey zone only ACL permission appears green) . Thank you

**Comment by fellchase** [comment]
Hi Saurabh

Thanks for using flumberbuckets, I have included ACL, WEBSITE, LOGGING and other tests just because one another tool used the same tests, I didn't want flumberbuckets to have less functionality than other tools on the market. Personally, I have never got any bounties off these tests. 

You can focus your energy on the buckets that are positive for UPLOAD, LIST & DELETE tests, then if those buckets turn out to belong to a bug bounty program then they should reward you high especially if they're using that bucket to host some files that users will download. 

For example, a company that sells their software like sublime text may want to host setup of their software on a S3 bucket since it's a huge file compared to HTML files they don't want the load on their website servers in such case if the S3 bucket, on which software setup is kept for downloading, turns out to be vulnerable to LIST + UPLOAD + DELETE. Then you can imagine a scenario where you delete original software setup with DELETE command and upload your own malicious executable there with UPLOAD command it can be a great way to distribute malware & exploit users trust of the company.

Focus your time on such scenarios that'd be far more rewarding

Thanks, if you have further queries DM on Twitter
